src/Entity/Partido.php
<?php

namespace App\Entity;

use App\Repository\PartidoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartidoRepository::class)]
class Partido
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Torneo $torneo = null;

    #[ORM\ManyToOne]
    private ?Jugador $jugador_1 = null;

    #[ORM\ManyToOne]
    private ?Jugador $jugador_2 = null;

    #[ORM\Column (nullable: true)]
    private ?int $etapa = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTorneo(): ?Torneo
    {
        return $this->torneo;
    }

    public function setTorneo(?Torneo $torneo): static
    {
        $this->torneo = $torneo;

        return $this;
    }

    public function getJugador1(): ?Jugador
    {
        return $this->jugador_1;
    }

    public function setJugador1(?Jugador $jugador_1): static
    {
        $this->jugador_1 = $jugador_1;

        return $this;
    }

    public function getJugador2(): ?Jugador
    {
        return $this->jugador_2;
    }

    public function setJugador2(?Jugador $jugador_2): static
    {
        $this->jugador_2 = $jugador_2;

        return $this;
    }

    public function getEtapa(): ?int
    {
        return $this->etapa;
    }

    public function setEtapa(int $etapa): static
    {
        $this->etapa = $etapa;

        return $this;
    }
}

src/Entity/Torneo.php
<?php

namespace App\Entity;

use App\Repository\TorneoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TorneoRepository::class)]
class Torneo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column]
    private ?bool $genero = null;

    #[ORM\Column]
    private ?int $cantidad = null;

    #[ORM\Column (nullable: true)]
    private ?int $etapas = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function isGenero(): ?bool
    {
        return $this->genero;
    }

    public function setGenero(bool $genero): static
    {
        $this->genero = $genero;

        return $this;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): static
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getEtapas(): ?int
    {
        return $this->etapas;
    }

    public function setEtapas(int $etapas): static
    {
        $this->etapas = $etapas;

        return $this;
    }
}

src/Form/TorneoType.php
<?php

namespace App\Form;

use App\Entity\Torneo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class TorneoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('genero', ChoiceType::class, [
                'choices' => [
                    'Masculino' => true,
                    'Femenino' => false,
                ],
            ])
            ->add('cantidad', ChoiceType::class, [
                'choices' => [
                    '4 Jugadores' => 4,
                    '8 Jugadores' => 8,
                    '16 Jugadores' => 16,
                    '32 Jugadores' => 32,
                ],
            ])
        ;

        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
            $torneo = $event->getData();
            $form = $event->getForm();

            if ($torneo instanceof Torneo && $torneo->getCantidad() !== null) {
                $cantidad = $torneo->getCantidad();
                $etapas = log($cantidad, 2);
                $etapas = ceil($etapas);

                $torneo->setEtapas($etapas);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Torneo::class,
        ]);
    }
}

src/Controller/TorneoController.php
<?php

namespace App\Controller;

use App\Entity\Torneo;
use App\Entity\InscripcionTorneo;
use App\Entity\Resultado;
use App\Form\TorneoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use App\Service\OrganizarPartidos;
use Symfony\Component\HttpFoundation\Request;

class TorneoController extends AbstractController
{
    #[Route('/torneo', name: 'app_torneo')]
    public function index(EntityManagerInterface $em, Request $request): Response
    {    
        try {
            $torneos = $em->getRepository(Torneo::class)->findBy([], [], 10); 
        } catch (\Exception $e) {
            return new Response('Se produjo un error al recuperar los torneos: ' . $e->getMessage(), Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        $torneo = new Torneo();
        $torneoForm = $this->createForm(TorneoType::class, $torneo);
        $torneoForm->handleRequest($request);

        if ($torneoForm->isSubmitted() && $torneoForm->isValid()) {
            $torneo = $torneoForm->getData();

            $em->persist($torneo);
            $em->flush();

            return $this->redirectToRoute('app_torneo');
        }

        return $this->render('torneo/index.html.twig', [
           'torneos'=>$torneos,
           'torneoForm'=>$torneoForm->createView()
        ]);
    }

    #[Route('/torneo/{torneo}', name: 'app_torneo_detalles', methods: ['GET'])]
    public function organizar(EntityManagerInterface $em,int $torneo, OrganizarPartidos $orgnizar): Response
    {

        $inscriptos = $em->getRepository(InscripcionTorneo::class)->findBy(['torneo'=>$torneo]);
        $resultados = $em->getRepository(Resultado::class)->findBy(['torneo'=>$torneo]);
        $torneo = $em->getRepository(Torneo::class)->find($torneo);
      
        // $partidos = $em->getRepository(Partido::class)->findBy(['etapa'=>$etapa, 'torneo'=>$torneo]);
        return $this->render('torneo/detalles.html.twig', [
            'inscriptos' => $inscriptos,
            'resultados' => $resultados,
            'torneo' => $torneo
         ]);
    }
}

templates/torneo/cargando.html.twig
{% extends 'base.html.twig' %}

{% block title %}Torneo{% endblock %}

{% block body %}
<style>
  
</style>

<div class="container">
    <br>
    <section class="alert alert-info">
        <h1 class="display-2">Resultados del sorteo</h1>
        <hr>

    <a class="btn btn-success" href="{{ path('app_torneo') }}">Volver</a>
    <a class="btn btn-success" href="{{ path('app_torneo') }}">Simalar partidos</a>
    </section>

    <section>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for partido in partidos %}
            <tr>
         
                <td>{{ partido.jugador1.nombre }}</td>
                <td> vs.</td>
                <td>{{ partido.jugador2.nombre }}</td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    </section>



</div>
{% endblock %}

templates/torneo/detalles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Torneo{% endblock %}

{% block body %}
<style>
  .botonera td{
    padding: 5px;
  }
</style>

<div class="container">

    <section class="alert alert-">
        <h1 class="display-1">Detalle del Torneo</h1>

        <br>

      <section class="alert alert-info">
      <h3 class="card-title">{{ torneo.nombre }}</h3>
      <strong>Jugadores: {{ torneo.cantidad }}</strong><br>
      <strong>Etapas: {{ torneo.etapas }}</strong><br>
      {% if torneo.genero == true %}
        <span class="badge rounded-pill text-bg-info">Masculino</span>
        <p style="margin-top:10px;">En el torneo masculino, la fuerza y la velocidad de desplazamiento son tomadas en cuenta para el partido</p>
      {% else %}
         <span class="badge rounded-pill text-bg-warning">Femenino</span>
         <p style="margin-top:10px;">En el torneo femenino, tiene como diferencial que se considera la reacción en vez de la fuerza y la velocidad</p>
       {% endif %}

        <hr>

        <table class="botonera">
          <td><button id="simularTorneoBtn" class="btn btn-primary">Simular torneo</button></td>
          <td><a href="{{ path('app_menu') }}" class="btn btn-dark">Volver al menú</a></td>
        </table>

        <!-- Modal para mostrar mensajes de éxito o error -->
        <div class="modal fade" id="resultadoModal" tabindex="-1" aria-labelledby="resultadoModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="resultadoModalLabel">Resultado de la simulación</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" id="resultadoModalBody">
                <!-- Aquí se mostrarán los mensajes de éxito o error -->
              </div>
            </div>
          </div>
        </div>
      </section>
    </section>
    
    <section>
      <h2 class="display-5">Resultados</h2>
      <hr>

          {% set etapasTotal = torneo.etapas %}
          {% if resultados is empty %}
            <div class="alert alert-warning col" role="alert">
                No hay Resultados.
            </div>
            
        
          {% else %}
          {% for etapa in range(1, torneo.etapas) %}
          
          <br>
          <div class="card">
            <h5 class="card-header">Etapa {{ etapa }}</h5>
            <div class="card-body">
             
          <table class="table table-sm">
            <tbody>
              {% for resultado in resultados|filter(r => r.etapa == etapa) %}
                <tr>
                  <td>
                    {{ resultado.partido.jugador1.nombre }} {{ resultado.partido.jugador1.apellido }}
                    {% if resultado.ganador == resultado.partido.jugador1 %}
                      <i class="fa-solid fa-medal"></i>
                    {% endif %}
                  </td>

                  <td>
                    {{ resultado.partido.jugador2.nombre }} {{ resultado.partido.jugador2.apellido }}
                    {% if resultado.ganador == resultado.partido.jugador2 %}
                      <i class="fa-solid fa-medal"></i>
                    {% endif %}
                  <td>
                    
                   
                </tr>
              {% endfor %}
            </tbody>
          </table>
         
     
        </div>
      </div>
        {% endfor %}
        {% endif %}

     
    </section>

    <section>
      <br>
      <h2 class="display-5">Inscriptos</h2>
      <hr>
      
      {% if inscriptos is empty %}
          <div class="alert alert-warning col" role="alert">
              No hay inscriptos.
          </div>
          <td><a href="{{ path('app_inscripcion') }}" class="btn btn-primary">ir a Inscripciones</a></td>
       
        {% else %}
      <div class="row row-cols-1 row-cols-md-4 row-cols-lg-5 row-cols-sm-1 g-4">
        
        {% for inscripto in inscriptos %}
          
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <i class="fa-solid fa-circle-user"></i>
                {{ inscripto.jugador1.nombre }} {{ inscripto.jugador1.apellido }}</h5>
                <hr>
              <table class="table table-sm">
  
                  <tr>
                    <td>Saque(servicio)</td>
                    <td>{{ inscripto.jugador1.saque }}</td>
                  </tr>
                  <tr>
                    <td>Fondo</td>
                    <td>{{ inscripto.jugador1.fondo }}</td>
                  </tr>
                  <tr>
                    <td>Volea</td>
                    <td>{{ inscripto.jugador1.volea }}</td>
                  </tr>
                  <tr>
                    <td>Movilidad</td>
                    <td>{{ inscripto.jugador1.movilidad }}</td>
                  </tr>
                  <tr>
                    <td>Resistencia</td>
                    <td>{{ inscripto.jugador1.resistencia }}</td>
                  </tr>
                  <tr>
                    <td>Velocidad</td>
                    <td>{{ inscripto.jugador1.velocidad }}</td>
                  </tr>
                  <tr>
                    <td>Fuerza</td>
                    <td>{{ inscripto.jugador1.fuerza }}</td>
                  </tr>
                  <tr>
                    <td>Reacción</td>
                    <td>{{ inscripto.jugador1.reaccion }}</td>
                  </tr>
   
              </table>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}
        
      </div>
    </section>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    
    $('#simularTorneoBtn').on('click', function() {
     
      var idTorneo = {{ torneo.id }};
      var data = {
        'torneo': idTorneo
      };

      $.ajax({
        url: '/simulaciones', 
        method: 'POST', 
        contentType: 'application/json', 
         data: JSON.stringify(data),
        success: function(response) {
        
          $('#resultadoModalBody').html('<p><i class="fa-regular fa-face-laugh-beam"></i> La simulacion se realizó con exito</p><p> <i class="fa-solid fa-baseball"></i> El Ganador del Torneo es ' + response.message + '</p>');
          $('#resultadoModal').modal('show');
        },
        error: function(xhr, status, error) {
         
          $('#resultadoModalBody').html('<p>' + xhr.responseJSON.error + '</p>');
          $('#resultadoModal').modal('show');
        }
      });
    });

     $('#resultadoModal').on('hidden.bs.modal', function() {
            location.reload(); 
        });
  });
</script>

{% endblock %}

templates/torneo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Torneo{% endblock %}

{% block body %}
<style>
  .botonera td{
    padding: 5px;
  }
</style>

<!-- Modal -->
<div class="modal fade" id="torneoModal" tabindex="-1" aria-labelledby="torneoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      {{ form_start(torneoForm) }}
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="torneoModalLabel">Nuevo Torneo</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="form-group">
          {{ form_label(torneoForm.nombre) }}
          {{ form_widget(torneoForm.nombre, {'attr': {'class': 'form-control'}}) }}
          {{ form_errors(torneoForm.nombre) }}
      </div>
      <br>
      <div class="form-group">
          {{ form_label(torneoForm.genero) }}
          {{ form_widget(torneoForm.genero, {'attr': {'class': 'form-control'}}) }}
          {{ form_errors(torneoForm.genero) }}
      </div>
      <br>
      <div class="form-group">
          {{ form_label(torneoForm.cantidad) }}
          {{ form_widget(torneoForm.cantidad, {'attr': {'class': 'form-control'}}) }}
          {{ form_errors(torneoForm.cantidad) }}
      </div>
      <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
      {{ form_end(torneoForm) }}
    </div>
  </div>
</div>

<div class="container">

    <section class="alert alert-">
        <h1 class="display-1">Torneos</h1>

        <br>

      <section class="alert alert-info">
        Los torneos tienen etapas determinas por la cantidad de participantes del mismo, para iniciar el torneo se debe contar con la cantidad de jugadores configurada al crear el torneo.
        <hr>

        <table class="botonera">
          <td><a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#torneoModal">Nuevo Torneo</a></td>
          <td><a href="{{ path('app_menu') }}" class="btn btn-dark">Volver al menú</a></td>
        </table>

        

      </section>
    </section>

    


    <section>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Tipo</th>
            <th scope="col">Jugadores</th>
            <th scope="col">Etapas</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for torneo in torneos %}
            <tr>
            <th scope="row">{{ torneo.id }}</th>
            <td>{{ torneo.nombre }}</td>
            <td>
             {% if torneo.genero == true %}
              <span class="badge rounded-pill text-bg-info">Masculino</span>
            {% else %}
              <span class="badge rounded-pill text-bg-warning">Femenino</span>
            {% endif %}
            </td>
            <td>{{ torneo.cantidad }}</td>
            <td>{{ torneo.etapas }}</td>
            <td>  <a href="{{ path('app_torneo_detalles', {'torneo': torneo.id}) }}" class="btn btn-success">Iniciar torneo</a>  </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    </section>
</div>
{% endblock %}